version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splitwise_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_DzGSQJ0s8KwN@ep-lingering-pine-ap9cegfg-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=tangerine_secret_key_123!
      - NODE_ENV=production
