version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: splitwise_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: splitwise_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/expense_tracker
      - JWT_SECRET=tangerine_secret_key_123!
      - NODE_ENV=production
    depends_on:
      - mongo

volumes:
  mongo_data:
